[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyls"
version = "0.1"

#[tool.setuptools.entry_points]
#console_scripts = [
#    "pyls = pyls:main_function"
#]
